import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Contact Us</li>
          <li>Blog</li>
        </ul>
      </nav>
      



      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting Coder
        </h1>

        <p className={styles.description}>
          A Blog For Coders
        </p>
        <div className="blogs">
          <div className="blogItem">
            <h2>Popular Blogs</h2>
<h3>C++ Learning Path in 2022</h3>
<p>c++ is a Very Memory Efficient Language</p>
          </div>
          <div className="blogItem">
<h3>Java Learning Path in 2022</h3>
<p> Java is Used In Android Development</p>
          </div>
          <div className="blogItem">
<h3>Python Learning Path in 2022</h3>
<p>Python is a Very Easy Language</p>
          </div>
          <div className="blogItem">
<h3>Kotlin Learning Path in 2022</h3>
<p> Kotlin is a Very New Language</p>
          </div>




        </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
